# Generated by Django 5.2 on 2025-05-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True)),
                ('lore', models.TextField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, max_length=255, null=True)),
                ('splash_art', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'champions',
            },
        ),
        migrations.CreateModel(
            name='CombatRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'combat_ranges',
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_modes',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Genders',
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ability_key', models.CharField(choices=[('passive', 'Passive'), ('q', 'Q'), ('w', 'W'), ('e', 'E'), ('r', 'R'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooldown', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='frontend.champion')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='ChampionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='frontend.champion')),
            ],
            options={
                'verbose_name_plural': 'Champion media',
                'db_table': 'champion_media',
            },
        ),
        migrations.CreateModel(
            name='ChampionSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='frontend.champion')),
            ],
            options={
                'db_table': 'champion_skins',
                'unique_together': {('champion', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChampionCombatRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_ranges', to='frontend.champion')),
                ('combat_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.combatrange')),
            ],
            options={
                'db_table': 'champion_combat_ranges',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('game_type', models.CharField(choices=[('champion', 'Champion'), ('ability', 'Ability'), ('item', 'Item')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('attempts_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('target_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_target', to='frontend.ability')),
                ('target_champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_target', to='frontend.champion')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gamemode')),
                ('target_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_target', to='frontend.item')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='ChampionGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='frontend.champion')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.gender')),
            ],
            options={
                'db_table': 'champion_genders',
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_type', models.CharField(choices=[('champion', 'Champion'), ('ability', 'Ability'), ('item', 'Item')], max_length=10)),
                ('guess_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.ability')),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.champion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='frontend.game')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.item')),
            ],
            options={
                'db_table': 'guesses',
            },
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='frontend.item')),
            ],
            options={
                'db_table': 'item_stats',
            },
        ),
        migrations.CreateModel(
            name='ChampionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='frontend.champion')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.position')),
            ],
            options={
                'db_table': 'champion_positions',
            },
        ),
        migrations.CreateModel(
            name='ChampionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='frontend.champion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.region')),
            ],
            options={
                'db_table': 'champion_regions',
            },
        ),
        migrations.CreateModel(
            name='ChampionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='frontend.champion')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.resource')),
            ],
            options={
                'db_table': 'champion_resources',
            },
        ),
        migrations.CreateModel(
            name='ChampionSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='frontend.champion')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.species')),
            ],
            options={
                'verbose_name_plural': 'Champion species',
                'db_table': 'champion_species',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.language')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.user'),
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('average_attempts', models.FloatField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='frontend.user')),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='ItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.item')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'item_translations',
                'unique_together': {('item', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GenderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.gender')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'gender_translations',
                'unique_together': {('gender', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GameModeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.gamemode')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'game_mode_translations',
                'unique_together': {('game_mode', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CombatRangeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('combat_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.combatrange')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'combat_range_translations',
                'unique_together': {('combat_range', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ChampionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('lore', models.TextField(blank=True, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.champion')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'champion_translations',
                'unique_together': {('champion', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ChampionSkinTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.championskin')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'champion_skin_translations',
                'unique_together': {('skin', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AbilityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.ability')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
            ],
            options={
                'db_table': 'ability_translations',
                'unique_together': {('ability', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MediaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.championmedia')),
            ],
            options={
                'db_table': 'media_translations',
                'unique_together': {('media', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PositionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.position')),
            ],
            options={
                'db_table': 'position_translations',
                'unique_together': {('position', 'language')},
            },
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.region')),
            ],
            options={
                'db_table': 'region_translations',
                'unique_together': {('region', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.resource')),
            ],
            options={
                'db_table': 'resource_translations',
                'unique_together': {('resource', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.language')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.species')),
            ],
            options={
                'db_table': 'species_translations',
                'unique_together': {('species', 'language')},
            },
        ),
    ]
