# settings.py dosyasını şu şekilde düzenleyin:

"""
Django settings for lolgame project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%&tg(r6i^7ylynoysui_4=w7l04bei$@$j06f4$0mvb^6%9llo"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*','https://lolgame.net']

CSRF_TRUSTED_ORIGINS = [
    'https://lolgame.net'
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    'django.contrib.sitemaps',
    "frontend",
    "api",
    "function"
]
SITE_ID = 1
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = "lolgame.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lolgame.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 'mysql.connector.django' yerine bu değeri kullanın
            'NAME': 'lolgame',
            'USER': 'lolgame',
            'PASSWORD': 'ytAXI03jSDUqcO6WMnUp',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                'auth_plugin': 'mysql_native_password',
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = True
LANGUAGE_COOKIE_NAME = "langs"
LANGUAGE_CODE = 'en'

# Özel dil kodları tanımlaması
from django.conf import global_settings

# Tüm özel dil kodları için tanımlamalar
EXTRA_LANG_INFO = {
    'zh': {
        'bidi': False,
        'code': 'zh',
        'name': 'Chinese',
        'name_local': '中文',
    },
    'jp': {
        'bidi': False,
        'code': 'jp',
        'name': 'Japanese',
        'name_local': '日本語',
    },
    'br': {
        'bidi': False,
        'code': 'br',
        'name': 'Brazilian Portuguese',
        'name_local': 'Português Brasileiro',
    },
}

# Django'nun dil bilgi sözlüğünü güncelle
import django.conf.locale
LANG_INFO = dict(django.conf.locale.LANG_INFO, **EXTRA_LANG_INFO)
django.conf.locale.LANG_INFO = LANG_INFO

# Desteklenen diller listesi - orijinal listesiyle aynı şekilde bırakıyoruz
LANGUAGES = [
    ('en', _('English')),
    ('de', _('German')),
    ('tr', _('Turkish')),
    ('es', _('Spanish')),
    ('it', _('Italian')),
    ('nl', _('Dutch')),
    ('pt', _('Portuguese')),
    ('fr', _('French')),
    ('ru', _('Russian')),
    ('br', _('Brazilian Portuguese')),
    ('zh', _('Chinese')),
    ('jp', _('Japanese')),
    ('ko', _('Korean')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'public/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'public')
]

LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365 * 5  # 5 yıl

LANGUAGE_COOKIE_SAMESITE = 'Lax'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"